service: cart-service-wertey
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev
  timeout: 10
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    PORT: ${env:PORT_DATABASE}
    NAME_DATABASE: ${env:NAME_DATABASE}
    USER_DATABASE: ${env:USER_DATABASE}
    PASSWORD_DATABASE: ${env:PASSWORD_DATABASE}

package:
  individually: true

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: ANY
          path: '/{proxy+}'