service: cart-service-wertey
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    PORT: ${env:PORT_DATABASE}
    NAME_DATABASE: ${env:NAME_DATABASE}
    USER_DATABASE: ${env:USER_DATABASE}
    PASSWORD_DATABASE: ${env:PASSWORD_DATABASE}

custom:
  webpack:
    webpackConfig: ./webpack.serverless.config.js
    includeModules: true

plugins:
  - serverless-offline

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: ANY
          path: /
          cors: true

      - httpApi:
          method: ANY
          path: '/{proxy+}'
          cors: true